### ISSUE TITLE
OSError when piping output from rf_logs.py

### ISSUE THREAD

**Issue by billdodd** [DMTF/Redfish-Tacklebox#32]
While doing some testing with rf_logs.py I discovered that if you pipe or redirect the output, you will get an OSError:

```
$ python3.8 rf_logs.py -u admin -p ******** -r https://127.0.0.5 | head -5
Traceback (most recent call last):
  File "rf_logs.py", line 61, in <module>
    redfish_utilities.print_log_entries( log_entries, args.details )
  File "~/Development/git/Redfish-Tacklebox/redfish_utilities/logs.py", line 79, in print_log_entries
    console_size = os.get_terminal_size()
OSError: [Errno 25] Inappropriate ioctl for device
```

Similar results for other useful commands like:

```
$ python3.8 rf_logs.py -u admin -p ******** -r https://127.0.0.5 > logs.out
$ python3.8 rf_logs.py -u admin -p ******** -r https://127.0.0.5 | grep unauthorized
```

After fixing that (by using shutil.get_terminal_size()), there was an extraneous BrokenPipeError when piping to `head`:

```
$ python3.8 rf_logs.py -u admin -p ******** -r https://127.0.0.5 | head -5
  Id    | Timestamp                 | Message
  1     | 2020-02-08T00:11:45Z      | User rfpv60c4 added by: admin.
  2     | 2020-02-08T00:11:45Z      | User rfpv60c4 deleted by: admin.
  3     | 2020-02-08T00:11:47Z      | Browser login failure from: 127.0.0.5(
  4     | 2020-02-08T00:25:32Z      | Browser login: admin - 127.0.0.5(DNS n
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
```

Fixed that by catching the BrokenPipeError and closing stderr just before exiting.

After those changes:

```
$ python3.8 rf_logs.py -u admin -p ******** -r https://127.0.0.5 | head -5
  Id    | Timestamp                 | Message
  1     | 2020-02-08T00:28:23Z      | User rfpv2ec8 added by: admin.
  2     | 2020-02-08T00:28:23Z      | User rfpv2ec8 modified by: admin.
  3     | 2020-02-08T00:28:23Z      | User rfpv2ec8 deleted by: admin.
  4     | 2020-02-08T00:28:24Z      | User rfpv7924 added by: admin.
```

**Comment by mraineri** [comment]
Reopening; changes to hide this exception were hiding all exceptions. Will need to revisit this.
