### ISSUE TITLE
rf_boot_override.py error handling

### ISSUE THREAD

**Issue by StackKorora** [DMTF/Redfish-Tacklebox#77]
```
$ rf_boot_override.py -u myuser -p mypass -r https://my.ip.addr -t badoption
Setting a one time boot for badoption...
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/redfish/bin/rf_boot_override.py", line 60, in <module>
    redfish_utilities.set_system_boot( redfish_obj, args.system, args.target, boot_enable, args.mode, uefi_target, boot_next )
  File "/home/user/miniconda3/envs/redfish/lib/python3.7/site-packages/redfish_utilities/systems.py", line 163, in set_system_boot
    raise ValueError( "{} is not an allowable override target ({})".format( ov_target, ", ".join( ov_target_values ) ) )
ValueError: badoption is not an allowable override target (None, Pxe, Floppy, Cd, Usb, Hdd, BiosSetup, Utilities, Diags, UefiShell, UefiTarget, SDCard, UefiHttp, RemoteDrive, UefiBootNext)
```
I think it would be a nicer experience to not have the excess error messages. The last line is a perfect explanation of what went wrong and what needs to change. The rest is not needed/helpful.

**Comment by mraineri** [comment]
Can certainly prune this in each of the scripts to only show the message at the end of the trace.

**Comment by StackKorora** [comment]
Thank you. I'm obviously working through the tools now and found that rf_manager_config.py is similar when I specify a bad interface for getnet. The last line is quite valuable but the rest doesn't add anything useful.
