### ISSUE TITLE
TransferProtocol error from rf_update.py

### ISSUE THREAD

**Issue by jcengland** [DMTF/Redfish-Tacklebox#91]
I got this error today, and found a similar issue in https://github.com/DMTF/Redfish-Tacklebox/issues/65 but the answer seemed to just be protocol could be NONE.  

If I pass in `protocol = "HTTP"` to the `simple_update` call, this error goes away.  If I don't make this change I get the following:

```
rf_update.py -u xxxxx -p xxxxxxxxx -r https://host1 -i http://192.168.1.251/fw-updates.itb
Traceback (most recent call last):
  File "/bin/rf_update.py", line 107, in <module>
    response = redfish_utilities.simple_update( redfish_obj, image_uri, targets = targets )
  File "/usr/lib/python3.6/site-packages/redfish_utilities/update.py", line 125, in simple_update
    verify_response( response )
  File "/usr/lib/python3.6/site-packages/redfish_utilities/messages.py", line 71, in verify_response
    raise RedfishOperationFailedError( "Operation failed: HTTP {}\n{}".format( response.status, exception_string ) )
redfish_utilities.messages.RedfishOperationFailedError: Operation failed: HTTP 400
The property TransferProtocol is a required property and must be included in the request.
The property TransferProtocol is a required property and must be included in the request.
```

This could be a red herring, no pun intended, since I am not a redfish nor a REST expert nor python for that matter.  I don't see anywhere what protocol gets set except to NONE and for me that seems to cause a failure.  Should `rf_update.py` work out of the box for most things assuming the redfish implementation is solid?  Thanks for your time and work on this project.

Clay

**Comment by jcengland** [comment]
This is my redfish implementation. Sorry closing.
